### PR TITLE
Punt datatype generation to Projector

### PR DESCRIPTION
**Pull request by thumphries**
WIP
/jury approved @charleso

### CODE REVIEW

**Comment by thumphries** [comment]
This would be a breaking change: each loom component's datatypes would be crammed into a single module. `Bikeshed.Data` `Manor.Data` etc.

This won't change your interactive processes, but may break code (I'll just fix it all, very mechanical)

**Comment by thumphries** [comment]
! @charleso just realised names like `Manor.Data` are not quite appropriate, any ideas?

**Comment by charleso** [comment]
@thumphries Not sure if you say my direct email - could we make it `Manor.Loom.Data` instead?

**Comment by charleso** [comment]
👍

**Pull request merged**
